config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => Maawol::Config.site_host

  root to: 'home#index'
  get 'cookie-acceptance',                     to: 'cookie_acceptance#new'
  get 'sitemap.xml', to: 'sitemap#index'

  resources :passwords, controller: 'passwords', only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: 'users', only: [:create] do
    resource :password, controller: 'passwords', only: [:edit, :update]
  end

  get 'sign_in' => 'sessions#new', as: 'sign_in'
  delete 'sign_out' => 'sessions#destroy', as: 'sign_out'
  get 'sign_up' => 'users#new', as: 'sign_up'

  namespace :admin do
    resources :users
    resources :subscribers
    resources :comps
    resources :authors
    resources :lessons
    resources :videos
    resources :audio_files
    resources :downloadables
    resources :stores
    resources :product_payments
    resources :subscription_options
    resources :users_subscription_payments
    resources :courses
    resources :root_categories
    resources :categories
    resources :tags
    resources :skill_levels
    resources :playlists
    resources :albums
    resources :stuck_questions
    resources :income_reports, only: [:index, :show]
    namespace :content_management do
      resources :content_blocks
      resources :pages
      resources :images
      get 'edit_nav/:slug', to: 'navbars#edit', as: :edit_navbar
      patch 'edit_nav/:id', to: 'navbars#update', as: :navbar
    end
    resources :site_settings
    resources :site_images
    put 'set_homepage_video', to: 'videos#set_for_homepage'
    put 'set_main_author', to: 'authors#set_main'
    get 'resource-counts', to: 'resource_counts#index'
    get 'help', to: 'help#show'
    root to: 'lessons#index'
  end

  post 'tmp-media', to: 'tmp_media#create'
  delete 'tmp-media/:id', to: 'tmp_media#destroy'

  resources :lessons
  get 'lessons/section/:root_category', to: 'lessons#index', as: :section, category: :all
  get 'lessons/section/:root_category/:category', to: 'lessons#index', as: :category
  get 'lessons/tag/:tag', to: 'lessons#index', as: :tag
  get 'lesson-suggestions', to: 'lesson_suggestions#index', as: :lesson_suggestions
  resources :courses
  get 'course/:slug', :to => 'courses#show', as: :course_by_slug

  resources :views
  resources :watch_laters
  resources :favourites
  resources :settings
  resources :comments
  patch  'update_password', to: 'settings#update_password'

  get 'home' => 'dashboard#index'
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'lesson-request' => 'contact#new', lesson_request: true
  get 'stuck' => 'contact#new', stuck: true
  get 'contact' => 'contact#new', as: :new_contact
  post 'contact' => 'contact#create', as: :contacts
  get 'categories' => 'categories#index'
  patch 'card_details', to: 'card_details#update', as: :update_card_details

  get 'paypal/success', to: 'paypal_callback#create'
  get 'paypal/cancel', to: 'paypal_callback#destroy', as: :cancel_paypal_payment

  resources :subscriptions
  get 'subscribe' => 'subscriptions#new', as: :subscribe
  post 'subscription_discount', to: 'subscription_discounts#create'
  get 'subscription_discount', to: 'subscription_discounts#show'
  get 'subscription_options', to: 'subscription_options#index'
  get 'subscription_option/:id', to: 'subscription_options#show'

  post 'chargebee', to: 'chargebee_webhooks#router'
  post 'paypal/webhook', to: 'paypal_callback#webhooks_router'

  get 'products', to: 'products#index'
  get 'basket', to: 'basket#show'
  patch 'add_product_to_basket', to: 'basket#update', method: :add
  patch 'remove_product_from_basket', to: 'basket#update', method: :remove
  delete 'clear_basket', to: 'basket#destroy'
  get 'file/:token', to: 'downloadables#show', as: :download_file
  get 'audio_file/:token', to: 'audio_files#show', as: :download_audio_file
  get 'checkout', to: 'checkout#new', as: :checkout
  get 'checkout/paypal/cancel', to: 'checkout#new', paypal_cancelled: true
  get 'single-checkout/:token', to: 'checkout#new', as: :file_basket
  post 'checkout', to: 'checkout#create', as: :process_checkout
  get 'checkout-complete', to: 'checkout#show', as: :checkout_complete
  get 'checkout/paypal/success', to: 'checkout#update'

  get 'store/:slug', to: 'stores#show', as: :store

  delete 'delete-account', to: 'users#destroy'

  get 'privacy-policy', to: 'privacy_policy#show', slug: 'privacy-policy'
  get 'terms-and-conditions', to: 'terms_and_conditions#show', slug: 'terms-and-conditions'
  get '*slug', to: 'content_management/pages#show', as: :cms_page, constraints: lambda { |req|
    req.path.exclude?('amazonaws.com') && req.path.exclude?('packs')
  }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < MaawolController
	before_action :require_login

	def new
		if current_user.has_recurring_subscription?
			redirect_to settings_path(preclick: :membership), alert: t('controllers.subscriptions.new.errors.already_recurring')
		else
			flash[:notice] = t('controllers.subscriptions.new.from_locked') if params[:from] && params[:from] == "locked_lesson"
		end
	end

	def create
		subscription_level = params[:users_subscription][:level]
		session_discount_code = session[:discount_code] || nil
		payment = params[:payment]

		if payment[:type] == 'paypal'	# PAYPAL PAYMENT
			options = {
				site_name: school_setting("site-name"),
				current_user: current_user,
				subscription_level: subscription_level,
				session_discount_code: session_discount_code || nil,
				return_url: "#{host}/paypal/success",
				cancel_url: "#{host}/paypal/cancel",
				currency_code: Maawol::Config.currency_code
			}
			remote_subscription = Payment::Paypal::Subscription.new(options).create
			respond_to do |format|
				if remote_subscription.error
					format.json { @status = :error; @error = "#{remote_subscription.error}"; }
				else
					redirect_url = remote_subscription.links.find{|v| v.method == "REDIRECT" }.href
					format.json { @status = :success; @paypal_redirect = redirect_url; }
				end
			end
		else	# CARD PAYMENT
	    if error_msg = Payment::Chargebee::Service.detect_card_errors(payment)
	    	respond_to do |format|
	    		format.html do
	    			flash[:error] = error_msg
	    			redirect_to settings_path
	    		end
	    		format.json { @status = :error; @error = "#{error_msg}"; }
	    	end
		  else
				begin
					options = {
						current_user: current_user,
						subscription_level: subscription_level,
						card_details: payment,
						session_discount_code: session_discount_code || nil
					}
					@subscription = Payment::Chargebee::Subscription.new(options).create
					if !@subscription.errors.any?
						session.delete(:discount_code)
						@subscription.send_to_store_front
						respond_to do |format|
							format.html do
								flash[:notice] = t('views.subscription.success')
								redirect_to "/lessons?paid=1"
							end
							format.json { @status = :success }
						end
					else
						respond_to do |format|
							@error = legible_form_errors(@subscription.errors)
							format.html do
								flash[:error] = @error
								redirect_to settings_path
							end
							format.json { @status = :error }
						end
					end
				rescue Exception => e
					error_msg = t('views.subscription.errors.card_fail')
					respond_to do |format|
						format.html do
							flash[:error] = error_msg
							redirect_to settings_path
						end
						format.json do
							@status = :error
							@error = error_msg
							@full_error = e.message
							@backtrace = e.backtrace
						end
					end
				end
			end
		end
	end

	def show
		respond_to do |format|
			format.json do
				@subscription = UsersSubscription.find_by_id(params[:id])
				if @subscription.nil? || (@subscription.user_id != current_user.id)
					@status = :error
					@message = t('views.account.subscription.error.auth')
				else
					@status = :success
				end
			end
		end
	end

	def update # cancel recurring billing
		respond_to do |format|
			@subscription = UsersSubscription.find_by_id(params[:id])
			format.json do
				if @subscription.nil? || (@subscription.user_id != current_user.id)
					@status = :error
					@message = t('views.account.subscription.cancellation.error.auth')
				else
					site_name = school_setting("site-name")
					if @subscription.cancel_recurring_billing(site_name)
						current_user.update_attribute(:status, :expiring)
						@status = :success
						@message = "#{t('views.subscription.recurring_cancelled')} #{@subscription.ends_at.strftime("%d %B, %Y")}"
						if SiteSetting.site_admin_gets_subscription_cancelled_email?
							AdminMailer.subscription_cancelled(@subscription).deliver_now
						end
					else
						@status = :error
						@message = t('views.subscription.errors.cancel_recurring')
					end
				end
			end
		end
	end
end

app/helpers/maawol/subscription_helper.rb
module Maawol
	module SubscriptionHelper
		def subscription_option_full_text(option)
			if option.days < 365
				"#{option.monthly_price("<span class='currency'>#{Maawol::Config.currency_symbol}</span>", true)}<span class='month'> / month</span>"
			else
				"#{option.yearly_price("<span class='currency'>#{Maawol::Config.currency_symbol}</span>", true)}<span class='month'> / year</span>"
			end
		end

		def monthly_fee
			if fee = SubscriptionOption.find_by(payment_system_plan: :monthly)
				number_to_currency(fee.price.round(2), unit: Maawol::Config.currency_symbol)
			end
		end
	end
end

app/views/subscriptions/_cancel_recurring.html.erb
<div class="modal fade recurring" id="cancelRecurringAreYouSureModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    	<div class="modal-header">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <i class="fas fa-times"></i>
        </button>
        <h3><%= t('views.account_settings.cancel_recurring_modal.title') %></h3>
      </div>

      <div class="modal-body">

        <div class="clearfix"></div>

        <h4><%= t('views.account_settings.cancel_recurring_modal.subtitle') %></h4>
        <p class="mb-2"><%= t('views.account_settings.cancel_recurring_modal.desc') %></p>

				<button id="cancel_recurring_confirm" class="btn btn-danger w-75">
          <span ng-hide="cancellingRecurringBilling">
            <%= t('views.account_settings.cancel_recurring_modal.buttons.ok') %>
          </span>
          <span ng-hide="!cancellingRecurringBilling">
            <span class="mr-2 text-white"><%= render partial: 'layouts/loader', locals: { size: :button } %></span>
            <%= t('views.account_settings.cancel_recurring_modal.buttons.processing') %>
          </span>
				</button>

				<button id="deactivate" class="btn btn-success w-75">
					<%= t('views.account_settings.cancel_recurring_modal.buttons.cancel') %>
				</button>

      </div>
    </div>
  </div>
</div>

app/views/subscriptions/new.html+mobile.erb
<% html_title "Subscribe" %>

<section id="subscription">
  <div class="container content_wrapper"
      id="subscribe"
      ng-controller="MobileSubscriptionsController"
      data-redirected-from="<%= params[:from] %>"
      data-redirected-message-profile_messaging="<%= t('views.subscription.messaging_restricted') %>"
      data-redirected-message-views="<%= t('views.subscription.visits_restricted') %>"
      data-redirected-message-favourites="<%= t('views.subscription.favourites_restricted') %>"
      data-redirected-message-messages="<%= t('views.subscription.messaging_restricted') %>"
      data-payment-error-prefix="<%= I18n.t('views.subscription.form.errors.prefix') %>"
      data-card-error-number-invalid="<%= I18n.t('views.subscription.form.errors.card_number') %>"
      data-card-error-expiry-invalid="<%= I18n.t('views.subscription.form.errors.expiry') %>"
      data-card-error-cv2-invalid="<%= I18n.t('views.subscription.form.errors.cv2') %>"
      data-server-error-options="<%= I18n.t('mobile.views.subscribe.error_loading_options') %>"
      data-discount-error-prefix="<%= I18n.t('views.subscription.discount.error.prefix') %>"
      data-discount-code="<%= session[:discount_code].present? ? session[:discount_code] : '' %>"
      data-discount-applying-text="<%= t('views.subscription.form.labels.discount_code.applying') %>"
      data-discount-applied-text="<%= t('views.subscription.form.labels.discount_code.applied') %>"
      data-daily-calculation-text="<%= t('views.subscription.summary.daily_calculation', currency_symbol: Maawol::Config.currency_symbol) %>">

      <flash-message></flash-message>

      <section id="choose_option" class="" ng-hide="slide != 'options'">
        <h2 class="section-title">
          <%= t('views.subscription.main_title', school: school_setting("site-name")) %>
        </h2>

        <% if notice %>
          <p class="container alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="container alert alert-danger"><%= alert %></p>
        <% end %>

        <h3 class="step_denoter" style="display: none"><b><%= t('views.defaults.step') %> 1.</b> <%= t('views.subscription.steps.one') %></h3>

        <h4><%= t('views.subscription.reasons.title') %></h4>
        <ul class="option_desc mb-4 pl-1">
          <li class="d-flex mb-2">
            <i class="fas fa-clipboard-check mr-2 pr-1 mt-2"></i>
            <span><%= t('views.subscribe_callout.items.library_access') %></span>
          </li>
          <li class="d-flex mb-2">
            <i class="fas fa-clipboard-check mr-2 pr-1 mt-2"></i>
            <span><%= t('views.subscribe_callout.items.one_on_one', name: Author.main_author.name) %></span>
          </li>
          <% if school_setting("facebook-page-url").present? %>
            <li class="d-flex mb-2">
              <i class="fas fa-clipboard-check mr-2 pr-1 mt-2"></i>
              <span><%= t('views.subscribe_callout.items.facebook_access') %></span>
            </li>
          <% else %>
            <li class="d-flex mb-2">
              <i class="fas fa-clipboard-check mr-2 pr-1 mt-2"></i>
              <span><%= t('views.subscribe_callout.items.much_more') %></span>
            </li>
          <% end %>
        </ul>

        <h4><%= t('views.subscription.choose.title') %></h4>
        <div class="subscription_option" ng-repeat="option in subscription_options" ng-class="{ 'most_popular': option.mostPopular, 'normal': !option.mostPopular }">

          <p id="most_popular" ng-class="{'selected': subscription.months == option.months }" ng-if="option.mostPopular"><%= t('views.subscription.options.most_popular') %></p>

          <label class="option pt-3" data-level="{{ option.level }}"
                  data-full-price="{{ option.fullPrice }}"
                  data-price="{{ option.price }}"
                  data-monthly-price="{{ option.monthlyPrice }}"
                  data-name="{{ option.monthsText }}"
                  data-discounted-price="{{ option.discountedPrice }}"
                  data-discounted-percentage="{{ option.discountedPercentage }}"
                  ng-class="{
                              'selected': subscription.level == option.level,
                              'normal': !option.mostPopular,
                              'most_popular': option.mostPopular
                            }">

            <input type="radio" value='{{ option.level }}' name='chosen_subscription' ng-model="subscription.level" />

            <h6>{{ option.description }}</h6>

            <h3 class="option_length" ng-if="!option.mostPopular" style="display: none">{{ option.name }}</h3>

            <h3 class="monthly_price" ng-bind-html="option.monthlyPriceFullText | rawHtml"></h3>
            <button class="button selector" data-level="{{option.level}}" style="display: none">
              <span ng-if="subscription.level != option.level"><%= t('views.subscription.options.select') %></span>
              <span ng-if="subscription.level == option.level"><%= t('views.subscription.options.selected') %></span>
           </button>
          </label>
        </div>

        <p id="discount_applied" ng-if="discount.applied" ng-bind-html="discount.description"></p>
        <form id="discount_form" ng-if="!discount.applied" class="d-none w-100">
          <input type="text" placeholder="<%= t('views.subscription.form.labels.discount_code.placeholder') %>" id="discount_code_input" ng-model="discount.code" />
          <button id="discount_code_button"><%= t('views.subscription.form.labels.discount_code.button') %></button>
        </form>

      </section>

      <section class="" ng-hide="slide != 'payment'">
        <h2 class="section-title"><%= t('views.subscription.summary.title') %></h2>
        <section id="discount_and_summary" class="">

          <div id="summary">
            <table cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td class="last_row">{{ subscription.name }}</td>
                <td class="right last_row"><%= Maawol::Config.currency_symbol %>{{ subscription.fullPrice }}</td>
              </tr>
              <tr ng-if="discount.applied && subscription.discounted.percentage > 0">
                <td class="last_row">Discount (-{{ subscription.discounted.percentage }}%)</td>
                <td class="right last_row">-<%= Maawol::Config.currency_symbol %>{{ subscription.discounted.price }}</td>
              </tr>
              <tr>
                <td class="total total_label"><%= t('views.subscription.summary.total') %></td>
                <td class="total right"><%= Maawol::Config.currency_symbol %>{{ total }}</td>
              </tr>
              <tr>
                <td colspan="2" id="summary_daily_calculation" class="right">
                 ({{ dailyPriceText }})
                </td>
              </tr>
            </table>
          </div>

          <p id="terms">* <%= t('views.subscription.small_print_terms_html', currency_symbol: Maawol::Config.currency_symbol) %></p>
        </section>

        <section id="payment">
         <h3 class="step_denoter" style="display: none"><b><%= t('views.defaults.step') %> 2.</b> <%= t('views.subscription.steps.two') %></h3>

         <form id="payment_form" name="payment_form" class="well" novalidate method="post" action="<%= subscriptions_path %>">
            <p id="selected_option">
              <span class="item_label" style="width: 30%;"><%= t('views.subscription.form.labels.selected') %>: </span>
              <span class="selected_months">{{subscription.name}} @</span>
              <span id="selected_total">
               <%= Maawol::Config.currency_symbol %>{{subscription.price}}
             </span>
            </p>

            <p>
              <a href='#' id="back_to_options" ng-if="subscription_options.length > 1">
                <%= t('views.subscription.back_to_options_html') %>
              </a>
            </p>

           <div class="form_item">
             <label for="choose_payment_type">
              <%= t('views.subscription.form.labels.card_type') %>
            </label>

            <ul id="choose_payment_type" class="w-100 d-flex justify-content-start subscribe">
              <li>
               <label class="payment_chooser d-flex justify-content-between">
                <input type="radio" name="payment_type" value="visa" ng-model="payment.type" class="mr-2" />
                <i class="fab fa-cc-visa"></i>
              </label>
            </li>
            <li>
              <label class="payment_chooser d-flex justify-content-between">
                <input type="radio" name="payment_type" value="mastercard" ng-model="payment.type" class="mr-2" />
                <i class="fab fa-cc-mastercard"></i>
              </label>
            </li>
            <% if use_paypal? %>
            <li>
              <label class="payment_chooser d-flex justify-content-between">
                <input type="radio" name="payment_type" value="paypal" ng-model="payment.type" class="mr-2" />
                <i class="fab fa-cc-paypal"></i>
              </label>
            </li>
            <% end %>
          </ul>
          </div>

          <% if use_paypal? %>
          <div ng-show="payment.type == 'paypal'">
            <button id="checkout_with_paypal" class="pay_btn" ng-if="!paying">
              <%= t('views.subscription.form.paypal.button') %>
            </button>
            <h5 ng-if="paying" id="paypal_forwarding" class="d-flex text-center">
              <span class="mr-1"><%= render partial: 'layouts/loader', locals: { size: :small } %></span>
              <span><%= t('views.subscription.form.paypal.processing') %></span>
            </h5>
          </div>
          <% end %>

          <div ng-hide="payment.type == 'paypal'">
           <div class="form_item">
            <label for="card_number">
             <%= t('views.subscription.form.labels.card_number') %>
           </label>

           <input type="text" id="card_number" ng-model="payment.cardNumber" />
          </div>


          <div class="form_item">
            <label for="expiry">
             <%= t('views.subscription.form.labels.expiration') %>
           </label>

           <%= select_month(Date.today, { use_two_digit_numbers: true }, { "ng-model": "payment.expiry.month" }) %>
           <%= select_year(Date.today, { start_year: Date.today.year, end_year: Date.today.year + 8 }, { "ng-model": "payment.expiry.year" }) %>
          </div>


          <div class="form_item">
            <label for="cv2">
              <%= t('views.subscription.form.labels.cv2') %>
            </label>
            <input type="text" id="cv2" class="small" ng-model="payment.cv2" />
          </div>

          <button type="submit" id="pay_btn" class="pay_btn btn btn-success"
                    data-style="expand-left"
                    ng-class="{ 'paying': paying == true }">
            <span ng-if="!paying"><%= t('views.defaults.subscribe').capitalize %></span>
            <span ng-if="paying == true">
              <span class="mr-2 text-white"><%= render partial: 'layouts/loader', locals: { size: :button } %></span>
              <%= t('views.subscription.form.labels.paying') %>
            </span>
          </button>
        </div>

        <div class="form_item" id="secured_by">
         <label>
          <%= t('views.subscription.form.labels.secured_by') %>
        </label>

        <div id="comodo">
          <%= image_tag 'subscribe/comodo.png', alt: 'Comodo' %>
        </div>
        </div>
      </form>
    </section>
  </section>

<%= render partial: "checkout/payment_error", locals: { current_user: current_user } %>

</section>